### ISSUE TITLE
Some Pirania and FBW tests failed

### ISSUE THREAD

**Issue by selankon** [libremesh/lime-app#347]
Some tests failed on my computer after https://github.com/libremesh/lime-app/commit/d71c2e831d925470501873c418e3e1e7b205e11d . FBW and Pirania related.

Aren't tests required to pass before a PR? 

```bash
➜ npm run test plugins/*

> preact-limeapp@0.2.25 test
> jest "plugins/lime-plugin-align" "plugins/lime-plugin-changeNode" "plugins/lime-plugin-fbw" "plugins/lime-plugin-firmware" "plugins/lime-plugin-ground-routing" "plugins/lime-plugin-locate" "plugins/lime-plugin-metrics" "plugins/lime-plugin-network-admin" "plugins/lime-plugin-node-admin" "plugins/lime-plugin-notes" "plugins/lime-plugin-pirania" "plugins/lime-plugin-remotesupport" "plugins/lime-plugin-rx"

 PASS  plugins/lime-plugin-pirania/src/screens/wellcomeScreenEditor.spec.js (5.563s)
 PASS  plugins/lime-plugin-firmware/firmware.spec.js (6.209s)
 FAIL  plugins/lime-plugin-pirania/src/screens/voucherList.spec.js
  ● voucher list › search by node hostname

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

  ● voucher list › search by voucher name

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

  ● voucher list › search only over filtered list

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

 FAIL  plugins/lime-plugin-fbw/src/FbwPage.spec.js (9.009s)
  ● Fbw Join Network Page › return to select action when cancel is pressed on scan list page

      208 |             await screen.findByRole('button', { name: /Cancel/i })
      209 |         )
    > 210 |         expect(await screen.findByText('Configure your network')).toBeInTheDocument();
          |                             ^
      211 |         expect(scanStop).toHaveBeenCalled()      
      212 |     })
      213 |

      at waitForWrapper (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByText (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at plugins/lime-plugin-fbw/src/FbwPage.spec.js:210:29

  ● Fbw Join Network Page › return to select action when cancel is pressed on join network page

      223 |             await screen.findByRole('button', { name: /Cancel/i })
      224 |         )
    > 225 |         expect(await screen.findByText('Configure your network')).toBeInTheDocument();
          |                             ^
      226 |
      227 |         expect(scanStop).toHaveBeenCalled()
      228 |     })

      at waitForWrapper (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByText (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at plugins/lime-plugin-fbw/src/FbwPage.spec.js:225:29

 PASS  plugins/lime-plugin-node-admin/src/screens/hotspot/hotspot.spec.js
 PASS  plugins/lime-plugin-locate/src/communityGeoJSON.spec.js
 PASS  plugins/lime-plugin-node-admin/nodeAdmin.spec.js
 PASS  plugins/lime-plugin-align/align.spec.js
 PASS  plugins/lime-plugin-pirania/src/screens/voucher.spec.js
 PASS  plugins/lime-plugin-pirania/nodeAdmin/PortalConfigPage.spec.js
 PASS  plugins/lime-plugin-node-admin/src/screens/password.spec.js
 PASS  plugins/lime-plugin-pirania/src/components/voucherListItem.spec.js
 PASS  plugins/lime-plugin-node-admin/src/screens/hotspot/src/components/testBoxes.spec.js
 PASS  plugins/lime-plugin-remotesupport/remoteSupport.spec.js
 PASS  plugins/lime-plugin-node-admin/src/screens/roamingAP.spec.js
 PASS  plugins/lime-plugin-remotesupport/src/remoteSupportApi.spec.js
 PASS  plugins/lime-plugin-pirania/src/screens/createVoucher.spec.js
 PASS  plugins/lime-plugin-pirania/src/screens/postCreate.spec.js
 PASS  plugins/lime-plugin-firmware/src/firmwareApi.spec.js
 PASS  plugins/lime-plugin-pirania/nodeAdmin/PortalConfigItem.spec.js
 PASS  plugins/lime-plugin-node-admin/src/screens/hostname.spec.js
 PASS  plugins/lime-plugin-pirania/src/screens/invalidateVoucher.spec.js
 PASS  plugins/lime-plugin-node-admin/src/layouts/configPageLayout.spec.js
 PASS  plugins/lime-plugin-pirania/src/components/timeAgo.spec.js
 PASS  plugins/lime-plugin-pirania/src/screens/editVoucher.spec.js

Summary of all failing tests
 FAIL  plugins/lime-plugin-pirania/src/screens/voucherList.spec.js
  ● voucher list › search by node hostname

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

  ● voucher list › search by voucher name

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

  ● voucher list › search only over filtered list

    expect(element).toBeInTheDocument()

    element could not be found in the document

      120 | 		expect(
      121 | 			await screen.findByTestId(`voucher-item-${v.id}`)
    > 122 | 		).toBeInTheDocument();
          | 		  ^
      123 | 	}
      124 | 	const otherVouchers = vouchers.filter(
      125 | 		v => expectedVouchers.indexOf(v) === -1

      at plugins/lime-plugin-pirania/src/screens/voucherList.spec.js:122:5

 FAIL  plugins/lime-plugin-fbw/src/FbwPage.spec.js (9.009s)
  ● Fbw Join Network Page › return to select action when cancel is pressed on scan list page

      208 |             await screen.findByRole('button', { name: /Cancel/i })
      209 |         )
    > 210 |         expect(await screen.findByText('Configure your network')).toBeInTheDocument();
          |                             ^
      211 |         expect(scanStop).toHaveBeenCalled()      
      212 |     })
      213 |

      at waitForWrapper (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByText (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at plugins/lime-plugin-fbw/src/FbwPage.spec.js:210:29

  ● Fbw Join Network Page › return to select action when cancel is pressed on join network page

      223 |             await screen.findByRole('button', { name: /Cancel/i })
      224 |         )
    > 225 |         expect(await screen.findByText('Configure your network')).toBeInTheDocument();
          |                             ^
      226 |
      227 |         expect(scanStop).toHaveBeenCalled()
      228 |     })

      at waitForWrapper (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at findByText (node_modules/@testing-library/preact/node_modules/@testing-library/dom/dist/query-helpers.js:101:33)
      at plugins/lime-plugin-fbw/src/FbwPage.spec.js:225:29


Test Suites: 2 failed, 23 passed, 25 total
Tests:       5 failed, 215 passed, 220 total
Snapshots:   0 total
Time:        24.9s
Ran all test suites matching /plugins\/lime-plugin-align|plugins\/lime-plugin-changeNode|plugins\/lime-plugin-fbw|plugins\/lime-plugin-firmware|plugins\/lime-plugin-ground-routing|plugins\/lime-plugin-locate|plugins\/lime-plugin-metrics|plugins\/lime-plugin-network-admin|plugins\/lime-plugin-node-admin|plugins\/lime-plugin-notes|plugins\/lime-plugin-pirania|plugins\/lime-plugin-remotesupport|plugins\/lime-plugin-rx/i.
```

**Comment by selankon** [comment]
This is fixed https://github.com/libremesh/lime-app/pull/348
