### ISSUE TITLE
"Access Vouchers" menu entry is present even if Pirania is not installed

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-app#384]
I just installed the LibreMesh 2020.3 release, that does not include Pirania (in includes just the things from this page: https://libremesh.org/development.html except lime-debug and adding lime-report).

The menu voice "Access Vouchers" is present, but when I click it the menu stops being responsive to the click and I have to reload the page.

![Screenshot from 2023-04-27 21-17-43](https://user-images.githubusercontent.com/1329018/234969225-8d9c8670-c0f1-4047-89d1-db8c031a8737.png)

Here you can see the "Access Voucher" at the bottom of the menu:

![Screenshot from 2023-04-27 21-18-05](https://user-images.githubusercontent.com/1329018/234969252-9f4520d4-3dc8-438e-81a4-545e451d5ac6.png)

And here is the page that just shows this waiting thing and the sandwitch menu button does not work anymore:

![Screenshot from 2023-04-27 21-19-24](https://user-images.githubusercontent.com/1329018/234969271-e18b4f8c-60ba-4ac6-92dc-802f93bd7126.png)

**Comment by ilario** [comment]
From Firefox console I can see this messages:

```
GET
http://10.13.2.154/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

Uncaught (in promise) TypeError: o is null
    Of http://10.13.2.154/app/bundle.d2584.js:2
    x http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    b http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    h http://10.13.2.154/app/bundle.d2584.js:2
    h http://10.13.2.154/app/bundle.d2584.js:2
    promise callback*d http://10.13.2.154/app/bundle.d2584.js:2
    setState http://10.13.2.154/app/bundle.d2584.js:2
    __ http://10.13.2.154/app/bundle.d2584.js:2
    N http://10.13.2.154/app/bundle.d2584.js:2
    notify http://10.13.2.154/app/bundle.d2584.js:2
    flush http://10.13.2.154/app/bundle.d2584.js:2
    flush http://10.13.2.154/app/bundle.d2584.js:2
    N http://10.13.2.154/app/bundle.d2584.js:2
    flush http://10.13.2.154/app/bundle.d2584.js:2
    promise callback*v http://10.13.2.154/app/bundle.d2584.js:2
    flush http://10.13.2.154/app/bundle.d2584.js:2
    batch http://10.13.2.154/app/bundle.d2584.js:2
    dispatch http://10.13.2.154/app/bundle.d2584.js:2
    setData http://10.13.2.154/app/bundle.d2584.js:2
    promise http://10.13.2.154/app/bundle.d2584.js:2
    promise callback*g http://10.13.2.154/app/bundle.d2584.js:2
    promise http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    promise http://10.13.2.154/app/bundle.d2584.js:2
    w http://10.13.2.154/app/bundle.d2584.js:2
    Z http://10.13.2.154/app/bundle.d2584.js:2
    g http://10.13.2.154/app/bundle.d2584.js:2
    fetch http://10.13.2.154/app/bundle.d2584.js:2
    fetch http://10.13.2.154/app/bundle.d2584.js:2
    optionalFetch http://10.13.2.154/app/bundle.d2584.js:2
    subscribe http://10.13.2.154/app/bundle.d2584.js:2
    N http://10.13.2.154/app/bundle.d2584.js:2
    v http://10.13.2.154/app/bundle.d2584.js:2
    b http://10.13.2.154/app/bundle.d2584.js:2
    b http://10.13.2.154/app/bundle.d2584.js:2
    setTimeout handler*n http://10.13.2.154/app/bundle.d2584.js:2
    diffed http://10.13.2.154/app/bundle.d2584.js:2
    diffed http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    b http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    b http://10.13.2.154/app/bundle.d2584.js:2
    _ http://10.13.2.154/app/bundle.d2584.js:2
    h http://10.13.2.154/app/bundle.d2584.js:2
    h http://10.13.2.154/app/bundle.d2584.js:2
bundle.d2584.js:2:252217
```

And from Chromium I get these messages:

```
bundle.d2584.js:2 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
DevTools failed to load source map: Could not load content for http://10.13.2.154/app/bundle.d2584.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.13.2.154/app/9.chunk.04b16.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
bundle.d2584.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sort')
    at s.Of [as constructor] (bundle.d2584.js:2:252222)
    at s.x [as render] (bundle.d2584.js:2:299859)
    at _ (bundle.d2584.js:2:297405)
    at b (bundle.d2584.js:2:293881)
    at _ (bundle.d2584.js:2:297637)
    at bundle.d2584.js:2:293212
    at Array.some (<anonymous>)
    at h (bundle.d2584.js:2:293105)
Of @ bundle.d2584.js:2
x @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
h @ bundle.d2584.js:2
Promise.then (async)
d @ bundle.d2584.js:2
s.setState @ bundle.d2584.js:2
o.__c.o.__ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
N @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
Promise.then (async)
v @ bundle.d2584.js:2
B5kz.t.flush @ bundle.d2584.js:2
B5kz.t.batch @ bundle.d2584.js:2
t.dispatch @ bundle.d2584.js:2
t.setData @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
Promise.then (async)
g @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
g @ bundle.d2584.js:2
t.fetch @ bundle.d2584.js:2
t.fetch @ bundle.d2584.js:2
t.optionalFetch @ bundle.d2584.js:2
t.subscribe @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
v @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
b @ bundle.d2584.js:2
setTimeout (async)
n @ bundle.d2584.js:2
requestAnimationFrame (async)
(anonymous) @ bundle.d2584.js:2
QRet._.options.diffed @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
S @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
S @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
h @ bundle.d2584.js:2
Promise.then (async)
d @ bundle.d2584.js:2
s.setState @ bundle.d2584.js:2
o.__c.o.__ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
N @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
Promise.then (async)
v @ bundle.d2584.js:2
B5kz.t.flush @ bundle.d2584.js:2
B5kz.t.batch @ bundle.d2584.js:2
t.dispatch @ bundle.d2584.js:2
t.setData @ bundle.d2584.js:2
t.setQueryData @ bundle.d2584.js:2
onSuccess @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
Promise.then (async)
A @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
Promise.then (async)
A @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
a.type @ bundle.d2584.js:2
f @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
v @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
b @ bundle.d2584.js:2
setTimeout (async)
n @ bundle.d2584.js:2
requestAnimationFrame (async)
(anonymous) @ bundle.d2584.js:2
QRet._.options.diffed @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
b @ bundle.d2584.js:2
_ @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
h @ bundle.d2584.js:2
Promise.then (async)
d @ bundle.d2584.js:2
s.setState @ bundle.d2584.js:2
t.routeTo @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
r @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
notifyListeners @ bundle.d2584.js:2
h @ bundle.d2584.js:2
(anonymous) @ bundle.d2584.js:2
confirmTransitionTo @ bundle.d2584.js:2
m @ bundle.d2584.js:2
v @ bundle.d2584.js:2
```
